import React, { useState } from "react";
import { Link } from "react-router-dom";
import { Bot, Stethoscope, Image } from "lucide-react";

const features = [
  {
    title: "Symptom Checker",
    desc: "Submit your symptoms and get a possible diagnosis generated by an intelligent ML model.",
    icon: <Stethoscope className="w-10 h-10 text-emerald-400" />,
    link: "/symptom-checker",
  },
  {
    title: "AI Chatbot",
    desc: "Chat with a smart virtual doctor to get instant medical advice using natural language understanding.",
    icon: <Bot className="w-10 h-10 text-sky-500" />,
    link: "/chatbot",
  },
  {
    title: "Image Analysis",
    desc: "Upload medical images like rashes or infections and let AI analyze patterns and suggest conditions.",
    icon: <Image className="w-10 h-10 text-pink-400" />,
    link: "/image-analysis",
  },
];

const faqs = [
  {
    q: "Is this chatbot a real doctor?",
    a: "No, it's powered by AI and ML models trained on medical data. It offers helpful suggestions, but it's not a replacement for a licensed doctor.",
  },
  {
    q: "Is my data safe?",
    a: "Yes! We prioritize privacy. Your data is stored securely and only used to enhance the chatbot’s accuracy.",
  },
  {
    q: "Does it cost anything?",
    a: "Nope, it’s completely free to use for now.",
  },
  {
    q: "Can I use it on mobile?",
    a: "Absolutely! The interface is fully responsive for phones, tablets, and desktops.",
  },
];

const FAQItem = ({ question, answer }) => {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-white/10 py-4">
      <button
        onClick={() => setOpen(!open)}
        className="flex justify-between items-center w-full text-left text-lg font-semibold text-slate-50 hover:text-sky-400 transition duration-300"
      >
        {question}
        <span className="ml-2 transform transition-transform duration-300">
          {open ? "−" : "+"}
        </span>
      </button>
      <div
        className={`overflow-hidden transition-all duration-500 ease-in-out ${
          open ? "max-h-40 mt-2" : "max-h-0"
        }`}
      >
        <p className="text-slate-400">{answer}</p>
      </div>
    </div>
  );
};

const Home = () => {
  // console.log(import.meta.env.VITE_API_URL);
  // console.log(import.meta.env.VITE_BACKEND_URL);
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-gray-900 to-slate-800 text-slate-50 px-6 py-16">
      <div className="max-w-6xl mx-auto text-center backdrop-blur-md bg-white/5 p-6 rounded-xl shadow-2xl shadow-pink-400/10">
        {/* Hero Section */}
        <h1 className="text-5xl md:text-6xl font-extrabold mb-4 drop-shadow-md text-violet-400 uppercase">
          Smart Medical Diagnosis <br />
          with AI
        </h1>
        <p className="text-xl text-slate-300 mb-12">
          Upload any medical image and ask your questions — powered by
          cutting-edge AI that delivers detailed insights instantly. Whether
          it’s skin or scans, get smart diagnostics right at your fingertips.
        </p>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {features.map((feature, index) => (
            <Link to={feature.link} key={index}>
              <div className="bg-white/5 backdrop-blur-md p-6 rounded-xl hover:scale-105 hover:bg-white/10 transition-all duration-300 shadow-md shadow-violet-500/20 cursor-pointer">
                <div className="flex justify-center mb-4">{feature.icon}</div>
                <h2 className="text-xl font-semibold text-slate-50 mb-2">
                  {feature.title}
                </h2>
                <p className="text-slate-300">{feature.desc}</p>
              </div>
            </Link>
          ))}
        </div>

        {/* How It Works */}
        <section className="text-left mb-16 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-violet-300 mb-4">
            🧠 How It Works
          </h3>
          <ul className="list-disc list-inside text-slate-400 space-y-2">
            <li>Describe your symptoms or select from a list.</li>
            <li>AI processes input using NLP & medical datasets.</li>
            <li>Optionally upload an image for visual diagnosis.</li>
            <li>
              Get disease predictions, health tips, or connect to a doctor.
            </li>
          </ul>
        </section>

        {/* Tech Behind It */}
        <section className="text-left mb-16 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-violet-300 mb-4">
            🔍 Tech Under the Hood
          </h3>
          <ul className="list-disc list-inside text-slate-400 space-y-2">
            <li>
              <strong>NLP:</strong> Understands your inputs in natural language.
            </li>
            <li>
              <strong>ML & Regression:</strong> For symptom-based predictions.
            </li>
            <li>
              <strong>LSTM:</strong> Predicts based on time-series health data.
            </li>
            <li>
              <strong>RAG:</strong> Retrieves relevant medical knowledge
              dynamically.
            </li>
          </ul>
        </section>

        {/* Why Us */}
        <section className="text-left mb-16 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-violet-300 mb-4">
            🌟 Why Choose Us?
          </h3>
          <ul className="list-disc list-inside text-slate-400 space-y-2">
            <li>24/7 accessible AI doctor</li>
            <li>Free to use, secure & smart</li>
            <li>Works across devices</li>
            <li>Improves over time with feedback</li>
          </ul>
        </section>

        {/* FAQs */}
        <section className="text-left mb-16 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-violet-300 mb-6">❓ FAQs</h3>
          {faqs.map((faq, index) => (
            <FAQItem key={index} question={faq.q} answer={faq.a} />
          ))}
        </section>

        {/* Contact Form */}
        {/* <section className="text-left mb-20 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-violet-300 mb-6">
            📩 Contact Us
          </h3>
          <form className="space-y-4">
            <input
              type="text"
              placeholder="Your Name"
              className="w-full bg-white/5 border border-white/20 text-white px-4 py-3 rounded-md focus:outline-none focus:ring-2 focus:ring-violet-500/60"
            />
            <input
              type="email"
              placeholder="Your Email"
              className="w-full bg-white/5 border border-white/20 text-white px-4 py-3 rounded-md focus:outline-none focus:ring-2 focus:ring-violet-500/60"
            />
            <textarea
              rows="4"
              placeholder="Your Message"
              className="w-full bg-white/5 border border-white/20 text-white px-4 py-3 rounded-md focus:outline-none focus:ring-2 focus:ring-violet-500/60"
            ></textarea>
            <button
              type="submit"
              className="bg-pink-500 text-white px-6 py-3 rounded-md font-semibold hover:bg-pink-600 transition shadow-md shadow-pink-400/30"
            >
              Send Message
            </button>
          </form>
        </section> */}

        {/* CTA */}
        <div className="mt-10">
          <Link to="/register">
            <button className="bg-violet-600 hover:bg-violet-700 text-white px-10 py-4 rounded-full text-lg font-bold shadow-lg shadow-violet-500/30 transition-all duration-300">
              Get Started Now
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
